apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-oke-canary-app-deployment
spec:
  selector:
    matchLabels:
      app: sample-oke-canary-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sample-oke-canary-app
    spec:
      containers:
        - name: sample-oke-canary-app
          # enter the path to your image, be sure to include the correct region prefix
          image: <OCI Region>.ocir.io/<NameSpace>/<Image REPO > :${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - cat
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: sample-oke-canary-app-service
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: sample-oke-canary-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-oke-canary-app-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  # tls:
  # - secretName: tls-secret
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sample-oke-canary-app-service
              port:
                number: 8080